fixup! pk11_uri: Visible string instead of oId

diff --git a/tests/tpem_encoder b/tests/tpem_encoder
--- a/tests/tpem_encoder
+++ b/tests/tpem_encoder
@@ -6,28 +6,31 @@ source "${TESTSSRCDIR}/helpers.sh"
 
 # We need to configure early loading otherwise no digests are loaded,
 # and all checks are skipped
-sed -e "s/#pkcs11-module-encode-key-uri-to-pem/pkcs11-module-encode-key-uri-to-pem = true/" \
+sed -e "s/#pkcs11-module-encode-provider-uri-to-pem/pkcs11-module-encode-provider-uri-to-pem = true/" \
     -e "s/#pkcs11-module-load-behavior/pkcs11-module-load-behavior = early/" \
     "${OPENSSL_CONF}" > "${OPENSSL_CONF}.encode_to_pem"
 OPENSSL_CONF=${OPENSSL_CONF}.encode_to_pem
+make-uri-pem() {
+    export LC_ALL=C
 
-make-pkey-pem() {
     URI=$1
     OUT=$2
+    DESC="${3:-PKCS#11 Provider URI v1.0}"
 
-    OID="06 03 55 04 53"
-    URI_HEX=$(printf '%s' "${URI}" | perl -lne 'print unpack "H*", $_')
+    DESC_HEX=$(printf '%s' "${DESC}" | perl -ne 'print unpack "H*", $_')
+    URI_HEX=$(printf '%s' "${URI}" | perl -ne 'print unpack "H*", $_')
     {
-        echo "-----BEGIN PRIVATE KEY PK11-URI-----"
-        printf '30 82 %04x %s 0c 82 %04x %s'  \
-               "$((${#URI} + 9))" \
-               "${OID}" \
+        echo "-----BEGIN PKCS#11 PROVIDER URI-----"
+        printf '30 82 %04x 1a 82 %04x %s 0c 82 %04x %s'  \
+               "$((${#URI} + ${#DESC} + 8))" \
+               "${#DESC}" \
+               "${DESC_HEX[*]}" \
                "${#URI}" \
                "${URI_HEX[*]}" \
             | tr -d ' ' \
-            | perl -lne 'print pack "H*", $_' \
-            | base64
-        echo "-----END PRIVATE KEY PK11-URI-----"
+	    | perl -ne 'print pack "H*", $_' \
+	    | base64
+        echo "-----END PKCS#11 PROVIDER URI-----"
     }  > "${OUT}"
 }
 
@@ -53,13 +56,13 @@ sign-verify() {
     rm "${TMP_FILE}"
 }
 
-title PARA "Test PEM Encoding RSA support"
-
-make-pkey-pem "${PRIURI}" "${TMPPDIR}/priuri-pkey.pem"
-sign-verify "${TMPPDIR}/priuri-pkey.pem" "${PUBURI}" "${TMPPDIR}/64krandom.bin"
-
 RANDOM_HEX=$(od -A n -N 15 -t x1 /dev/random)
 export LABEL_SUFFIX_URI=${RANDOM_HEX// /}
+
+title PARA "Test PEM Encoding RSA support"
+
+make-uri-pem "${PRIURI}" "${TMPPDIR}/priuri-pkey.pem"
+sign-verify "${TMPPDIR}/priuri-pkey.pem" "${PUBURI}" "${TMPPDIR}/64krandom.bin"
 
 export ALGORITHM=rsa
 export ALGORITHM_OPT=rsa_keygen_bits:2048
@@ -69,16 +72,15 @@ genpkey -propquery "provider=pkcs11"
         -pkeyopt "pkcs11_uri:pkcs11:object=Test-PEM-Encode-RSA-${LABEL_SUFFIX_URI}"
         -out "${TMPPDIR}/rsa-pkey-uri.pem"'
 
-grep -e "-----BEGIN PRIVATE KEY PK11-URI-----" "${TMPPDIR}/rsa-pkey-uri.pem"
+grep -e "-----BEGIN PKCS#11 PROVIDER URI-----" "${TMPPDIR}/rsa-pkey-uri.pem"
 
 sign-verify "${TMPPDIR}/rsa-pkey-uri.pem" \
             "pkcs11:object=Test-PEM-Encode-RSA-${LABEL_SUFFIX_URI}" \
             "${TMPPDIR}/64krandom.bin"
 
-
 title PARA "Test PEM Encoding EC support"
 
-make-pkey-pem "${ECPRIURI}" "${TMPPDIR}/ecpriuri-pkey.pem"
+make-uri-pem "${ECPRIURI}" "${TMPPDIR}/ecpriuri-pkey.pem"
 sign-verify "${TMPPDIR}/ecpriuri-pkey.pem" "${ECPUBURI}" "${TMPPDIR}/64krandom.bin"
 
 export ALGORITHM=EC
@@ -89,30 +91,70 @@ genpkey -propquery "provider=pkcs11"
         -pkeyopt "pkcs11_uri:pkcs11:object=Test-PEM-Encode-EC-${LABEL_SUFFIX_URI}"
         -out "${TMPPDIR}/ec-pkey-uri.pem"'
 
-grep -e "-----BEGIN PRIVATE KEY PK11-URI-----" "${TMPPDIR}/ec-pkey-uri.pem"
+grep -e "-----BEGIN PKCS#11 PROVIDER URI-----" "${TMPPDIR}/ec-pkey-uri.pem"
 
 sign-verify "${TMPPDIR}/ec-pkey-uri.pem" \
             "pkcs11:object=Test-PEM-Encode-EC-${LABEL_SUFFIX_URI}" \
             "${TMPPDIR}/64krandom.bin"
 
 
+title PARA "Test visible string has to match"
+make-uri-pem "${PRIURI}" "${TMPPDIR}/priuri-wrong-version-key.pem" "PKCS#11 Provider URI v2.0"
+ossl '
+storeutl
+	-out "${TMPPDIR}/storeutl-priuri-wrong-version-key.txt"
+	"${TMPPDIR}/priuri-wrong-version-key.pem"' || :
+DATA=$(cat "${TMPPDIR}/storeutl-priuri-wrong-version-key.txt")
+if [[ ! ${DATA} =~ "Total found: 0" ]]; then
+    echo "Should fail because visible string does not match"
+    exit 1
+fi
+
+make-uri-pem "${PRIURI}" "${TMPPDIR}/priuri-too-long-key.pem" "PKCS#11 Provider URI v1.0-INVALID"
+ossl '
+storeutl
+	-out "${TMPPDIR}/storeutl-priuri-too-long-key.txt"
+	"${TMPPDIR}/priuri-too-long-key.pem"' || :
+DATA=$(cat "${TMPPDIR}/storeutl-priuri-too-long-key.txt")
+if [[ ! ${DATA} =~ "Total found: 0" ]]; then
+    echo "Should fail because visible string does not match"
+    exit 1
+fi
+
+make-uri-pem "${PRIURI}" "${TMPPDIR}/priuri-too-short-key.pem" "PKCS#11 Provider URI v1"
+ossl '
+storeutl
+	-out "${TMPPDIR}/storeutl-priuri-too-short-key.txt"
+	"${TMPPDIR}/priuri-too-short-key.pem"' || :
+DATA=$(cat "${TMPPDIR}/storeutl-priuri-too-short-key.txt")
+if [[ ! ${DATA} =~ "Total found: 0" ]]; then
+    echo "Should fail because visible string does not match"
+    exit 1
+fi
+
+
+title PARA "Test public key is usable"
+make-uri-pem "${PUBURI}" "${TMPPDIR}/puburi-key.pem"
+ossl '
+storeutl
+	-out "${TMPPDIR}/storeutl-puburi-key.txt"
+	"${TMPPDIR}/puburi-key.pem"'
+DATA=$(cat "${TMPPDIR}/storeutl-puburi-key.txt")
+if [[ ! ${DATA} =~ "Total found: 1" ]]; then
+    echo "Should return public key"
+    exit 1
+fi
+ossl 'storeutl "${TMPPDIR}/puburi-key.pem"' | grep "Total found: 1"
+
+
 title PARA "Test ambiguous key is unusable"
 
-make-pkey-pem "${BASEURI}" "${TMPPDIR}/baseuri-key.pem"
+make-uri-pem "${BASEURI}" "${TMPPDIR}/baseuri-key.pem"
 FAIL=0
 ossl '
 pkey -in "${TMPPDIR}/baseuri-key.pem"' || FAIL=1
 if [ $FAIL -eq 0 ]; then
-    echo "Should fail because the pem references multiple and/or non-private keys"
-    exit 1
-fi
-
-make-pkey-pem "${PUBURI}" "${TMPPDIR}/puburi-key.pem"
-FAIL=0
-ossl '
-pkey -in "${TMPPDIR}/puburi-key.pem"' || FAIL=1
-if [ $FAIL -eq 0 ]; then
-    echo "Should fail because the pem references multiple and/or non-private keys"
+    echo "Should fail for now URI from PEM need to be unique"
     exit 1
 fi
 
